---
title: "Въведение в анализ на времеви редове"
author: "Boyko Amarov"
date: "10/12/2021"
output: html_document
---

# Time series in R

```{r}
library(xts)
library(ggplot2)

bitcoins <- read.csv(
  'https://s3.eu-central-1.amazonaws.com/sf-timeseries/data/bitcoin2017-06-01-2017-11-13.csv', 
  stringsAsFactors = FALSE
)
bc_ts <- xts(bitcoins$close, order.by = as.Date(bitcoins$Index))
```

$$
y_{1}, y_{2}, y_{3}, \ldots, y_{T}\\
y_{t}, t = 1,\ldots, T
$$
In the bitcoins example $T = 117$. $y_1 = 2475.248, y_2 = 2688.172, \ldots, y_{117} = 6535.948$.

Looking from Nov 13th 2017: what was the value on the previous trading day? Answer
by simply looking in the table: $y_{117 - 1} = y_{116} = 6622.517$. 

$$
y_{t}, t = 1,\ldots, T\\
y_{t - 1}: \text{ first lag of } y_{t}\\
y_{t - 2}: \text{ second lag of } y_{t}
$$

```{r}
bc_ts_l1 <- lag(bc_ts)

tmp <- cbind(bc_ts, bc_ts_l1)

ggplot(data = tmp, aes(x = bc_ts_l1, y = bc_ts)) +
  geom_point() +
  labs(
    x = expression(y[t-1]),
    y = expression(y[t])
  )
```

