---
title: "03-ARIMA-basics"
author: "Boyko Amarov"
date: "11/2/2021"
output: html_document
---

# Autoregressive processes

Time series process: sequence of random variables

$$
y_1, y_2,\ldots,y_{T}
$$

Statistical properties:

1. Expected value
$$
E(y_t) = ?
$$
2. Variance

$$
Var(y_t) = E[(y_{t} - E(y_t))^2]
$$

3. Autocovariances/autocorrelations of time series

$$
Cov(y_t, y_{t - 1}) \text{ 1st order autocovariance}\\
Cov(y_t, y_{t - 2}) \text{ 2nd order autocovariance}\\
\vdots\\
Cov(y_t, y_{t - k}) \text{ k-th order autocovariance}\\
\rho(y_{t}, y_{t - 1}) = \frac{Cov(y_t, y_{t - 1})}{Var(y_t)} \text{ 1st order autocorrelation}\\
\rho(y_{t}, y_{t - 2}) = \frac{Cov(y_t, y_{t - 2})}{Var(y_t)} \text{ 2st order autocorrelation}\\
\vdots\\
\rho(y_{t}, y_{t - k}) = \frac{Cov(y_t, y_{t - k})}{Var(y_t)} \text{ k-th order autocorrelation}\\
$$
```{r}
## For illustration only

n <- 100

sim_data <- expand_grid(
  mu = c(0, 10),
  sigma = c(1, 3),
  t = 1:100
) %>%
  mutate(
    y = rnorm(n(), mean = mu, sd = sigma),
    sigma_lab = paste0("sigma = ", sigma),
    mu_lab = paste0("mu = ", mu)
  )

sim_data %>%
  ggplot(aes(x = t, y = y, color = mu_lab)) +
  geom_point(size = 1 / 2) +
  geom_line() +
  facet_wrap(~sigma_lab) +
  labs(
    x = "t",
    y = expression(y[t])
  )
```
```{r}
sim_data %>%
  group_by(mu_lab, sigma_lab) %>%
  summarise(
    Average = mean(y),
    StdDev = sd(y)
  )
```
Covariance

$$
\begin{aligned}
  y_{1,t} & = e_{1, t}\\
  y_{2, t} & = 2 y_{1, t} + e_{2,t}
\end{aligned}
$$

```{r}
n <- 100
y1 <- rnorm(n = n, mean = 0, sd = 1)
y2 <- rnorm(n = n, mean = 0, sd = 1)

tibble(y1, y2) %>%
  ggplot(aes(x = y1, y = y2)) +
    geom_point()

cov(y1, y2)
cor(y1, y2)
```


## AR(1)

$$
y_{t} = 2 + 0.5y_{t - 1} + e_{t}
$$
$e_t$ is a purely random process (white noise process).

$$
E(e_t) = 0\\
Var(e_t) = \sigma^2\\
Cov(e_t, e_{t - k}) = 0, k \neq 0
$$
$$
e_{t} \sim WN(\sigma^2)
$$







