---
title: "Untitled"
author: "Boyko Amarov"
date: "12/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xts)
library(tidyverse)
library(forecast)

dt <- read_csv("https://raw.githubusercontent.com/feb-uni-sofia/timeseries-2021-2022/main/data/gdp_bg_qrt_2000-2017.csv")

gdp <- xts(dt$GDP, order.by = as.yearqtr(dt$Index, format = "%YQ%q"))
```

```{r}
plot(gdp)
```

Growth series

$$
y_1, y_2, \ldots, y_{T}\\
g_{t} = \frac{y_{t} - y_{t - 1}}{y_{t - 1}}
$$
$$
g_{2} = 100 \times \frac{10961 - 10306}{10306} = 6.35
$$

$$
g_{t} = \log(y_{t}) - \log(y_{t - 1})
$$
```{r}
## We use stats::lag in order to make sure that we use the
## lag function from the stats package

gdp_l1 <- stats::lag(gdp)
growth_1 <- log(gdp) - log(gdp_l1)
head(growth_1)
plot(growth_1)
```
Growth series comparing the value of GDP a quarter with the same quarter
during the previous year.


$$
g_{t} = \log(y_{t}) - \log(y_{t - 4})
$$
```{r}
gdp_l4 <- stats::lag(gdp, 4)
growth_4 <- log(gdp) - log(gdp_l4)
head(growth_4)
plot(growth_4)
```

```{r}
?acf
acf(growth_4, na.action = na.pass)
pacf(growth_4, na.action = na.pass)
```

Fit an AR(1) model to the data

```{r}
fit_ar1 <- arima(growth_4, order = c(1, 0, 0))
fit_ar1
```

```{r}
tmp <- Arima(growth_4, order = c(1, 0, 0))
tmp
```

```{r}
## Prediction for one period after the 
## end of the observed series
predict(fit_ar1, n.ahead = 80)
```

Approximate 95% interval for the expected value one period ahead of $t$.

$$
[\hat{y}_t - 2 SE(\hat{y}_t), \hat{y}_t - 2 SE(\hat{y}_t)]
$$
$$
[\hat{y}_{t + 1} - 2 SE(\hat{y}_{t + 1}), \hat{y}_{t + 1} - 2 SE(\hat{y}_{t + 1})]
$$
$$
[0.037 - 2\cdot 0.0175, 0.037 + 2\cdot 0.0175] = [0.002, 0.072]
$$

$$
[\hat{y}_{t + 2} - 2 SE(\hat{y}_{t + 2}), \hat{y}_{t + 2} - 2 SE(\hat{y}_{t + 2})]
$$
$$
[0.0368 - 2 \cdot 0.022, 0.0368 + 2 \cdot 0.022] = [-0.0072, 0.0808]
$$

```{r}
## Prediction for 40 periods after the 
## end of the observed series
predict(fit_ar1, n.ahead = 80)
```

```{r}
tsdiag(fit_ar1)
```

Ljung-Box test

Convention: reject the null hypothesis if p-value < 0.05

$$
H_0: \rho_1 = 0\\
H_1: \rho_1 \neq 0\\
$$

$$
H_0: \rho_1 = \rho_2 = 0\\
H_1: \text{at least one of } \rho_1, \rho_2 \neq 0\\
$$
$$
H_0: \rho_1 = \rho_2 = ... = \rho_k = 0\\
H_1: \text{at least one of } \rho_1, \rho_2, \ldots, \rho_k \neq 0\\
$$
