---
title: "Untitled"
author: "Boyko Amarov"
date: "12/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xts)
library(tidyverse)

dt <- read_csv("https://raw.githubusercontent.com/feb-uni-sofia/timeseries-2021-2022/main/data/gdp_bg_qrt_2000-2017.csv")

gdp <- xts(dt$GDP, order.by = as.yearqtr(dt$Index, format = "%YQ%q"))
```

```{r}
plot(gdp)
```
Растеж (growth) на БВП

$$
y_1, y_2, y_3, \ldots, y_T\\
растеж = \frac{\text{стойност днес} - \text{стойност вчера}}{\text{стойност вчера}}
$$
Пример: растеж във второто тримесечие на 2000 г. спрямо първото тримесечие
на 2000 г.
$$
\frac{10961 - 10306}{10306}\times 100 = 6.3
$$

$$
\frac{y_{t} - y_{t - 1}}{y_{t}} \times 100
$$
100 -> 120, растеж 20%, 120 -> 96, растеж -20%

За малки промени на времевия ред
$$
\frac{y_{t} - y_{t - 1}}{y_{t}} \times 100 \approx 100(\log(y_t) - \log(y_{t - 1}))
$$
```{r}
growth_1 <- 100 * (log(gdp) - log(stats::lag(gdp, 1)))
growth_1
plot(growth_1)
```

Растеж спрямо същото тримесечие в предходната година
$$
\frac{y_{t} - y_{t - 4}}{y_{t}} \times 100 \approx 100(\log(y_t) - \log(y_{t - 4}))
$$

```{r}
growth_2 <- 100 * (log(gdp) - log(stats::lag(gdp, 4)))
growth_2
plot(growth_2)
```

$$
r_{t} = y_{t} - \hat{y}_{t}
$$

Корелации

```{r}
?acf
acf(growth_2, na.action = na.pass)
pacf(growth_2, na.action = na.pass)
```


```{r}
fit_ar1 <- arima(growth_2, order = c(1, 0, 0))
```

```{r}
fit_ar1
tsdiag(fit_ar1)
```

Ljung-Box тест

Първи ред:

$$
H_0: \rho_1 = 0\\
H_1: \rho_1 \neq 0
$$
Конвенция: отхвърляме $H_0$ при p-value < 0.05.

Втори ред
$$
H_0: \rho_1 = \rho_2 = 0\\
H_1: \text{Поне едно от } \rho_1, \rho_2 \neq 0
$$
к-ти ред

$$
H_0: \rho_1 = \rho_2 = \ldots = \rho_k = 0\\
H_1: \text{Поне едно от } \rho_1, \rho_2, \ldots, \rho_k \neq 0
$$

```{r}
predict(fit_ar1, n.ahead = 2)
```

```{r}
mean(growth_2, na.rm = TRUE)
```


Прогнозен интервал
$$
[\hat{y}_{t + 1} - 2 SE(\hat{y}_{t+1}), \hat{y}_{t + 1} + 2 SE(\hat{y}_{t+1})]
$$
$$
[3.72 - 2 \times 1.75, 3.72 + 2 \times 1.75] = [0.22, 7.22]
$$

95% прогнозен интервал
$$
[\hat{y}_{t + 2} - 2 SE(\hat{y}_{t+2}), \hat{y}_{t + 2} + 2 SE(\hat{y}_{t+2})]
$$

$$
[3.68 - 2 \times 2.259, 3.68 + 2 \times 2.259] = [-0.838, 8.198]
$$
$$
y_{t} = 3.5257 + 0.8152y_{t - 1} + u_{t}, u_{t} \sim WN(\sigma^2 = 3.066)
$$

```{r}
n <- 71 - 4

u_t_sim <- rnorm(n = n, sd = sqrt(3.066))

bg_gdp_growth_sim <- 3.5257 + arima.sim(
  model = list(ar = c(0.8152)),
  n = n,
  innov = u_t_sim
  )
plot(bg_gdp_growth_sim)
```




