---
title: "Въведение в анализ на времеви редове"
author: "Boyko Amarov"
date: "10/12/2021"
output: html_document
---

# Времеви редове в R

```{r}
library(xts)
library(ggplot2)

bitcoins <- read.csv(
  'https://s3.eu-central-1.amazonaws.com/sf-timeseries/data/bitcoin2017-06-01-2017-11-13.csv', 
  stringsAsFactors = FALSE
)
bc_ts <- xts(bitcoins$close, order.by = as.Date(bitcoins$Index))
```


$$
y = (y_{1}, y_{2}, y_{3}, \ldots, y_{T})
$$

$$
y_{t}, t = 1,\ldots,T\\
y_{t - 1}: \text{първи лаг на } y_t \\
y_{t - 2}: \text{втори лаг на } y_t
$$

В случая с Bitcoin $T = 117$.

```{r}
# Първи лаг на биткойн времевия ред
bc_ts_l1 <- lag(bc_ts)
bc_ts_l2 <- lag(bc_ts, k = 2)
bc_all_lags <- cbind(bc_ts, bc_ts_l1, bc_ts_l2)
```

```{r}
mean(bc_ts_l1, na.rm = TRUE)
```

```{r}
ggplot(data.frame(x = bc_ts_l1, y = bc_ts), aes(x = x, y = y)) + 
  geom_point() + 
  ggtitle('Scatterplot на USD/BTC днешна и вчерашна стойност.') +
  ylab('USD/BTC t') + 
  xlab('USD/BTC (t - 1)')
```

# Симулация 

$$
y_1, y_2, \ldots, y_T, T = 100
$$

```{r}
runif(n = 1, min = 10, max = 20)
```


```{r}
# Изтегляме сто стойности от стандартно нормално разпределение

xrandom <- rnorm(n = 100)
ts_random <- xts(xrandom, order.by = seq.Date(from = as.Date("2017-06-01"), by = "day", length.out = 100))
```

```{r}
plot(ts_random)
```

```{r}
ts_random_l1 <- lag(ts_random)
ts_all_lags <- cbind(ts_random, ts_random_l1)

ggplot(ts_all_lags, aes(x = ts_random_l1, y = ts_random)) + 
  geom_point() + 
  ggtitle('') +
  ylab('y[t]') + 
  xlab('y[t - 1]')
```
Два свята: математика и наблюдения

$$
y_{1}, y_{2}, \ldots, y_{T}
$$

## Математика

1. Средно ниво (математическо очакване)

$$
E(y_t)
$$
2. Дисперсия (колко различни са стойностите)

$$
Var(y_t) \text{ дисперсия, variance}
$$
3. Зависимости между наблюденията

$$
Cov(y_{t}, y_{t- 1})\\
Cov(y_{t}, y_{t - 2}) \\
\vdots
$$

## Наблюдения

1. Средна стойност

$$
\bar{y} = \frac{1}{T}\sum_{t = 1}^{T} y_{t}
$$

2. Емпирична дисперсия (sample variance)

$$
S^2_{y} = \frac{1}{T} \sum_{t = 1}^{T}(y_{t} - \bar{y}) ^2\\
S_y = \sqrt{S^2_{y}} \text{ емпирично стандартно отклонение}
$$
3. Емпирична ковариация (sample covariance)

$$
S^2_{x, y} = \frac{1}{T}\sum_{t = 1}^{T}(x_t - \bar{x})(y_t - \bar{y})
$$

Упражнение

$$
y_1 = 2, y_2 = 3, y_3 = 10\\
T = 3
$$

$$
\bar{y} = (2 + 3 + 10) / 3 = 5
$$

$$
S^2_{y} = \frac{1}{3}\left(
(y_1 - \bar{y})^2 + (y_2 - \bar{y})^2 + (y_3 - \bar{y})^2
\right) = \\
\frac{1}{3}\left(
(2 - 5)^2 + (3 - 5)^2 + (10 - 5)^2
\right) = \\
\frac{1}{3}\left(
9 + 4 + 25
\right) = 38 / 3 \approx 12.66 \\
$$

```{r}
y <- c(2, 3, 10)
mean(y)
var(y)
```

```{r}
?var
```

